FROM <image>:<tag>

RUN <install some dependencies>

CMD <command that is executed on `docker container run`>

# All instructions in a Dockerfile except CMD (and one other that we will learn about soon) 
# are executed during build time. CMD is executed when we call docker run, unless we overwrite it.
